---
- name: Provision development VM for django-lti-launch
  hosts: default
  become: yes

  tasks:

    - name: add PostgreSQL 9.5 repos
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5' state=present

    - name: add PostgreSQL 9.5 key
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

    - name: upgrade existing packages
      apt: upgrade=yes update_cache=yes

    - name: install needed apt packages
      apt: name={{ item }} state=present
      with_items:
        - python-apt
        - python3
        - python3-dev
        - python3-pip

    - name: install PostgreSQL 9.5
      apt: name={{ item }}
      with_items:
        - postgresql-9.5
        - libpq-dev

    - name: install psycopg2 (for Ansible)
      apt: name=python-psycopg2

    - name: install virtualenv for Python 3
      pip: name=virtualenv executable=pip3

    - name: install needed pip packages
      pip:
        chdir: yes
        executable: pip3
        requirements: requirements.txt
        virtualenv: /home/vagrant/.virtualenvs/django-lti-launch
        virtualenv_python: python3

    - name: create vagrant Postgres user
      postgresql_user: name=vagrant role_attr_flags=SUPERUSER
      become_user: postgres

    - name: create django_lti_launch database
      postgresql_db: name=django_lti_launch owner=vagrant
      become_user: postgres

    - name: have PostgreSQL listen to all interfaces
      lineinfile:
        dest: /etc/postgresql/9.5/main/postgresql.conf
        line: "listen_addresses = '*'"
      notify: restart postgres

    - name: allow PostgreSQL connections from VirtualBox host
      lineinfile:
        dest: /etc/postgresql/9.5/main/pg_hba.conf
        line: "host\tall\tall\t10.0.2.2/32\ttrust"
      notify: restart postgres

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
