---
- name: Provision development VM for django-lti-launch
  hosts: default
  become: yes

  tasks:

    - name: upgrade existing packages
      apt: upgrade=yes update_cache=yes cache_valid_time=86400

    - name: install needed apt packages
      apt: name={{ item }} state=present
      with_items:
        - python-psycopg2  # for Ansible PG modules
        - python3
        - python3-dev
        - python3-pip
        - postgresql
        - libpq-dev

    - name: install virtualenv for Python 3
      pip: name=virtualenv executable=pip3

    - name: install needed pip packages
      pip:
        chdir: yes
        executable: pip3
        requirements: requirements.txt
        virtualenv: /home/vagrant/.virtualenvs/django-lti-launch
        virtualenv_python: python3

    - name: create vagrant Postgres user
      postgresql_user: name=vagrant role_attr_flags=SUPERUSER
      become_user: postgres

    - name: create django_lti_launch database
      postgresql_db: name=django_lti_launch owner=vagrant
      become_user: postgres

    - name: have PostgreSQL listen to all interfaces
      lineinfile:
        dest: /etc/postgresql/9.3/main/postgresql.conf
        line: "listen_addresses = '*'"
      notify: restart postgres

    - name: allow PostgreSQL connections from VirtualBox host
      lineinfile:
        dest: /etc/postgresql/9.3/main/pg_hba.conf
        line: "host\tall\tall\t10.0.2.2/32\ttrust"
      notify: restart postgres

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
