---
- name: Provision development VM for django-lti-launch
  hosts: default
  become: yes

  tasks:
    - name: install needed apt packages
      apt: name={{ item }} state=present
      with_items:
        - python3
        - python3-dev
        - python3-pip

    - name: install virtualenv for Python 3
      pip: name=virtualenv executable=pip3
      
    - name: install needed pip packages
      pip:
        chdir: yes
        executable: pip3
        requirements: requirements.txt
        virtualenv: /home/vagrant/.virtualenvs/django-lti-launch
        virtualenv_python: python3
