# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltilaunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ltitoolconsumergroup',
            options={'verbose_name': 'LTI tool consumer group'},
        ),
        migrations.AlterModelOptions(
            name='ltiuser',
            options={'verbose_name': 'LTI user'},
        ),
    ]
