# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltilaunch', '0002_ltitoolprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIToolConsumerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ltitoolconsumer',
            name='matcher_class_name',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='ltitoolconsumer',
            name='consumer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ltilaunch.LTIToolConsumerGroup'),
        ),
    ]
