# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 22:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTITenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_short_name', models.CharField(max_length=50)),
                ('tenant_description', models.TextField(blank=True)),
                ('oauth_consumer_key', models.TextField()),
                ('oauth_consumer_secret', models.TextField()),
                ('tool_consumer_instance_guid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_launch_parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_launch_time', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTITenant')),
            ],
        ),
    ]
