# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 17:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ltilaunch.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIToolConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('oauth_consumer_key', models.TextField(default=ltilaunch.utils.generate_random_string, unique=True, verbose_name='OAuth consumer key')),
                ('oauth_consumer_secret', models.TextField(default=ltilaunch.utils.generate_random_string, verbose_name='OAuth consumer secret')),
                ('tool_consumer_instance_guid', models.TextField(verbose_name='Tool consumer instance GUID')),
                ('match_guid_and_consumer', models.BooleanField(default=True, verbose_name='Match GUID and OAuth consumer')),
                ('recent_nonces', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=10)),
            ],
            options={
                'verbose_name': 'LTI tool consumer',
            },
        ),
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lti_user_id', models.TextField()),
                ('last_launch_parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_launch_time', models.DateTimeField()),
                ('lti_tool_consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIToolConsumer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ltiuser',
            unique_together=set([('lti_tool_consumer', 'lti_user_id')]),
        ),
    ]
