# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ltilaunch', '0001_initial'), ('ltilaunch', '0002_auto_20160524_1629'), ('ltilaunch', '0003_ltitoolconsumer_tool_consumer_instance_guid'), ('ltilaunch', '0004_auto_20160524_2021'), ('ltilaunch', '0005_auto_20160524_2031'), ('ltilaunch', '0006_auto_20160524_2032')]

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIToolConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('oauth_consumer_key', models.TextField()),
                ('oauth_consumer_secret', models.TextField()),
                ('tool_consumer_instance_guid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_launch_parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_launch_time', models.DateTimeField()),
                ('lti_tool_consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIToolConsumer')),
                ('lti_user_id', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='ltitoolconsumer',
            name='tool_consumer_instance_guid',
        ),
        migrations.AddField(
            model_name='ltitoolconsumer',
            name='recent_nonces',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=10),
        ),
        migrations.AddField(
            model_name='ltitoolconsumer',
            name='tool_consumer_instance_guid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ltitoolconsumer',
            name='oauth_consumer_key',
            field=models.TextField(unique=True),
        ),
        migrations.RemoveField(
            model_name='ltitoolconsumer',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='ltiuser',
            unique_together=set([('lti_tool_consumer', 'lti_user_id')]),
        ),
        migrations.RenameField(
            model_name='ltiuser',
            old_name='lti_tool_consumer',
            new_name='tool_consumer_instance_guid',
        ),
        migrations.AlterUniqueTogether(
            name='ltiuser',
            unique_together=set([('tool_consumer_instance_guid', 'lti_user_id')]),
        ),
    ]
