# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltilaunch', '0001_initial_squashed_0006_auto_20160524_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiuser',
            name='lti_user_id',
            field=models.TextField(),
        ),
    ]
